### ISSUE TITLE
Draggable dialogbox

### ISSUE THREAD

**Issue by bitdom8** [mattjennings/svelte-modals#6]
**Is your feature request related to a problem? Please describe.**
A draggable box may help to obtain good results as such user experience

**Describe the solution you'd like**
If it is beyond modals would help to customise

```
<Modals>
  <div
    slot="backdrop"
    class="backdrop"
		transition:fade
    on:click={closeModal}
  />
</Modals>
```

**Comment by mattjennings** [comment]
Sorry, I don't quite understand the exact request here. Are you looking for functionality to drag modals around the page?

**Comment by bitdom8** [comment]
Yes, you may have been unsure not understanding. Because you are right what I have asked. Thanks

**Comment by mattjennings** [comment]
Gotcha. The functionality and styling of the modals are outside of the scope for this library, but since it gives you full control over your components, adding that functionality yourself would be trivial. 

For example, you could follow the tutorial here for creating a `use:pannable` action and add that to your Modal components

https://svelte.dev/tutorial/actions
